version: 2.1

orbs:
  # SEE: https://circleci.com/orbs/registry/orb/codecov/codecov
  codecov: codecov/codecov@1

jobs:
  # SEE: https://circleci.com/docs/2.0/workflows/#fan-outfan-in-workflow-example
  # SEE: https://circleci.com/docs/2.0/caching/

  test:
    docker:
      # SEE: https://circleci.com/docs/2.0/circleci-images/#python
      - image: circleci/python:3.10
    steps:
      - checkout
      - run: mkdir test-reports
      - run: &pip-config
          name: Write PIP config
          command: |
            mkdir -p ~/.config/pip/
            cat > ~/.config/pip/pip.conf \<< EOF
            [global]
            extra-index-url = ${GEMFURY_READ_PIP_URL:-https://pip.ad.synthego.com}
            progress_bar = off
            EOF

      - run: &pip-req-dev
          name: Install Python deps in a venv
          command: |
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install --upgrade setuptools_scm
            python -m pip install -r test/requirements-dev.txt
      - run:
          name: Coverage
          command: |
            . venv/bin/activate
            cd test
            coverage run
            coverage report
            coverage xml
            cp coverage.xml ../../test-reports/coverage.xml
      - codecov/upload:
          file: test/coverage.xml

  publish:
    docker:
      # SEE: https://circleci.com/docs/2.0/circleci-images/#python
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: *pip-config
      - run: *pip-req-dev
      - run:
          name: Write PyPI config
          command: |
            cat > ~/.pypirc \<< EOF
            [distutils]
            index-servers =
                fury
            [fury]
            repository: https://pypi.fury.io/synthego/
            username: ${GEMFURY_PUBLISH_TOKEN}
            password: n/a
            EOF
      - run:
          name: Publish model
          command: |
            . venv/bin/activate
            cd model/propeller/model
            python setup.py sdist upload -r fury
      - run:
          name: Publish instrument
          command: |
            . venv/bin/activate
            cd instrument/propeller/instrument
            python setup.py sdist upload -r fury
      - run:
          name: Publish operations
          command: |
            . venv/bin/activate
            cd operations/propeller/operations
            python setup.py sdist upload -r fury
      - run:
          name: Publish test
          command: |
            . venv/bin/activate
            cd test/propeller/test
            python setup.py sdist upload -r fury

workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish
