version: 2.1

jobs:
  build-and-test:
    machine:
      image: android:2022.08.1

    steps:
      - checkout
      - run:
          name: Do it
          command: echo "Do it"
      - run:
          command: echo Echo-${CIRCLE_NODE_INDEX}

workflows:
  sample:
    jobs:
      - build-and-test
