version: 2.1

jobs:
  build:
    docker:
     # - image: cimg/python:3.9.5-node
      - image: cimg/python:3.8
    resource_class: martincircleci/martin
    steps:
      - checkout
      - run:
          command: |-
            python3 -m venv venv
            . venv/bin/activate
            pip3 install --upgrade pip
            cat local_requirements.txt requirements.txt > full_requirements.txt
            pip3 install -r full_requirements.txt
          name: Install Requirement
      #- run:
          #command: sleep 5000
          #name: Sleep

            
