version: 2.1

jobs:
  build-and-test:
    docker:
      image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Message
          command: node --version

workflows:
  sample:
    jobs:
      - build-and-test
