version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
    machine: true
    
    steps:
      - checkout
      - run:
          name: Do it
          command: echo "Do it"

workflows:
  sample:
    jobs:
      - build-and-test
