version: 2.1

jobs:
  build-and-test:
    docker:
      - image: "cimg/node:lts"
    steps:
      - checkout
      - run:
          name: Message
          command: node --version

workflows:
  version: 2
  sample:
    jobs:
      - build-and-test
