version: 2.1

executors:
  deploy_image:
    docker:
      - image: ${AWS_ACCOUNT_NUMBER}.dkr.ecr.${ECR_AWS_REGION}.amazonaws.com/${ENVIRONMENT}/circlecipython-image/python311:latest
        aws_auth:
          aws_access_key_id: $AWS_ERC_ACCESS_KEY
          aws_secret_access_key: $AWS_ERC_SECRET_KEY

jobs:
  deploy:
    executor: deploy_image
    parameters:
      lambda:
        type: string
    steps:
      - attach_workspace:
          at: ~/
      - run: deploy_function.py --function << parameters.lambda >>

workflows:
  production-environment:
    jobs:
      - deploy:
          context: prod-aws-app-circleci
          filters:
            branches:
              only:
                - master
          name: "deploy-<< matrix.lambda >>"
          matrix:
            parameters:
              lambda: [ monitor ]
