version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.5-node
    steps:
      - checkout
      - run:
          name: Install
          command: |
            sudo apt-get update
            sudo apt-get install python-dev libjpeg-dev libfreetype6-dev zlib1g-dev python-dev build-essential