version: 2.1

jobs:
  build-and-test:
    machine:
      image: circleci/classic:201707-01
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Do it
          command: echo "Do it"
      - run:
          command: echo ${CIRCLE_NODE_INDEX}

workflows:
  sample:
    jobs:
      - build-and-test
