version: 2.1
orbs:
  android: circleci/android@1.0.3
jobs:
  build-and-test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: Message
          command: echo "Only Master?"

workflows:
  sample:
    jobs:
      - build-and-test
