version: 2.1
orbs:
  android: circleci/android@1.0.3
jobs:
  build-and-test:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: Looking for previous build with workspace
          command: echo ${CIRCLE_WORKFLOW_WORKSPACE_ID}

workflows:
  sample:
    jobs:
      - build-and-test
